// Plant image mapping
const plantImageMap = {
  // Specific plants
  'Glossy Buckthorn': 'glossyBuckthorn',
  'Golden Shower': 'goldenShower',
  'Loquat': 'loquat',
  'Apocynum': 'apocynum',
  'Bahama Maidenbush': 'bahamaMaidenbush',
  'Bouchea': 'bouchea',
  'Bouchetia': 'bouchetia',
  'Broadleaf False Carrot': 'broadleafFalseCarrot',
  'Calamint': 'calamint',
  'Chelsau': 'chelsau',
  'Chisos Mountain Pricklypear': 'chisosMountainPricklypear',
  'Costus': 'costus',
  'Cup Lichen': 'cupLichen',
  'Diplotomma Lichen': 'diplotommaLichen',
  'Duchesne River Twinpod': 'duchesneRiverTwinpod',
  'Dudley\'s Swordfern': 'dudleysSwordfern',
  'Dwarf Umbrella-sedge': 'dwarfUmbrellasedge',
  'Eastern Fournerved Daisy': 'easternFournervedDaisy',
  'Few-flower Fumitory': 'fewflowerFumitory',
  'Greenspot Nightshade': 'greenspotNightshade',
  'Hairyseed Paspalum': 'hairyseedPaspalum',
  'Hoary Tansyaster': 'hoaryTansyaster',
  'Indusiella Moss': 'indusiellaMoss',
  'Janusia': 'janusia',
  'Jau Jau': 'jauJau',
  'Johnston\'s Phlox': 'johnstonsPhlox',
  'Junghuhn\'s Sphagnum': 'junghuhnsSphagnum',
  'Melaspilea Lichen': 'melaspileaLichen',
  'Northern Wildrice': 'northernWildrice',
  'Palmer\'s Zinnia': 'palmersZinnia',
  'Parry\'s Lipfern': 'parrysLipfern',
  'Prairie Bishop': 'prairieBishop',
  'Prinkava\'s Prickleypear': 'prinkavasPrickleypear',
  'Puerto Rico Indigoberry': 'puertoRicoIndigoberry',
  'Script Lichen': 'scriptLichen',
  'Sedge': 'sedge',
  'Showy Draba': 'showyDraba',
  'Sonoran Water-willow': 'sonoranWaterwillow',
  'Spotless Balm': 'spotlessBalm',
  'Staghorn Clubmoss': 'staghornClubmoss',
  'Streambank Cyanea': 'streambankCyanea',
  'Szechuan White Birch': 'szechuanWhiteBirch',
  'Tropical False Goldeneye': 'tropicalFalseGoldeneye',
  'Umbrella Indian Mallow': 'umbrellaIndianMallow',
  'Waioli Valley Maiden Fern': 'waioliValleyMaidenFern',
  'Walpole\'s Poppy': 'walpolesPoppy',
  'Willow Cyanea': 'willowCyanea',
  'Winged Wattle': 'wingedWattle',
  'Wood Lily': 'woodLily',
  'Yellow Coralroot': 'yellowCoralroot',
  'Yellow Pond-lily': 'yellowPondlily',
  
  // Original sample plants
  'Tomato': 'hobartFarmImg',
  'Carrot': 'hobartFarmImg',
  'Cucumber': 'hobartFarmImg',
  'Apple': 'osoberryImg',
  'Strawberry': 'osoberryImg',
  'Blueberry': 'osoberryImg',
  'Rose': 'nooktaRoseImg',
  'Tulip': 'tulipImg',
  'Orchid': 'nooktaRoseImg',
  'Lettuce': 'hobartFarmImg',
  'Spinach': 'hobartFarmImg',
  'Broccoli': 'hobartFarmImg',
  'Orange': 'osoberryImg',
  'Raspberry': 'osoberryImg',
  'Cherry': 'osoberryImg',
  'Daisy': 'nooktaRoseImg',
  'Lily': 'nooktaRoseImg',
  'Sunflower': 'sunflowerImg',
};

export default plantImageMap;